name: uav
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - python-decouple
      - matplotlib
      - numpy
      - pandas
      - pyyaml
      - munch
      - pyparsing
      - pyulog
